CREATE TABLE `repos_log`(
    `id` int(11) NOT NULL,
    `uid` int(11) NOT NULL,
    `uname` varchar(40) NOT NULL,
    `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
    `updated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
    `pushed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
    `name` varchar(100) NOT NULL,
    `full_name` varchar(150) NOT NULL,
    `description` text,
    `default_branch` varchar(20) NOT NULL,
    `private` tinyint(1) DEFAULT 0,
    `fork` tinyint(1) DEFAULT 1,
    `homepage` text,
    `language` varchar(100),
    `forks_cnt` int(11) DEFAULT 0,
    `stars_cnt` int(11) DEFAULT 0,
    `watch_cnt` int(11) DEFAULT 0,
    KEY `idx_id`(`id`),
    KEY `idx_created`(`created`),
    KEY `idx_updated`(`updated`),
    KEY `idx_name`(`uname`, `name`),
    KEY `idx_fullname`(`full_name`),
    KEY `idx_language`(`language`),
    KEY `idx_forks_cnt`(`forks_cnt`),
    KEY `idx_stars_cnt`(`stars_cnt`),
    KEY `idx_watch_cnt`(`watch_cnt`)
)Engine=MyISAM DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
